FROM node:20

WORKDIR /usr/src/app

COPY app-api/package*.json ./

RUN npm install

COPY app-api ./

RUN npm run build

RUN npm install -g migrate-mongo

EXPOSE 3000

CMD ["sh", "-c", "npx migrate-mongo up && npm start"]
