version: '3.8'

services:
  db:
    image: postgres:16
    container_name: nerd-code-db-container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - nerd-code-network

  backend:
    container_name: nerd-code-backend-api-container
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3030:3000"
    volumes:
      - .:/opt/nerd-code-backend-api-container
    env_file:
      - .env
    networks:
      - nerd-code-network

  nginx:
    container_name: ner-code-nginx-container
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3040:80"
    volumes:
      - .:/opt/visualizerfrontend
    networks:
      - nerd-code-network

  redis:
    image: redis:7.4.0
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass A3UEbYaagT
    volumes:
      - .:/opt/redis

volumes:
  postgres_data:

networks:
  nerd-code-network:
    driver: bridge